Repository bakery-blueprint/different-dimension-derby, pull requests merged in 2022-01, with the labels that each got.

#1 week01 정리
  doc/demo/week01/README.MD
Labels: note

#2 DDD 1주차
  doc/hotire/week00/README.md
  doc/hotire/weeke01/README.md
  src/main/java/com/github/bakery/ddd/hotire/week1/ImmutableOrderImpl.java
  src/main/java/com/github/bakery/ddd/hotire/week1/Money.java
  src/main/java/com/github/bakery/ddd/hotire/week1/MutableOrder.java
  src/main/java/com/github/bakery/ddd/hotire/week1/MutableOrderImpl.java
  src/main/java/com/github/bakery/ddd/hotire/week1/Order.java
  src/main/java/com/github/bakery/ddd/hotire/week1/OrderLine.java
  src/main/java/com/github/bakery/ddd/hotire/week1/OrderState.java
Labels: documentation, enhancement, note

#3 빵 카페 과제 추가 🧁🥮🍰 🍩
  doc/homework/README.md
Labels: documentation, enhancement, note

#5 1주차 과제
  build.gradle
  src/main/java/com/github/bakery/ddd/hotire/README.md
  src/main/java/com/github/bakery/ddd/hotire/week2/domain/material/Bread.java
  src/main/java/com/github/bakery/ddd/hotire/week2/domain/material/Dough.java
  src/main/java/com/github/bakery/ddd/hotire/week2/domain/material/DoughMaterial.java
  src/main/java/com/github/bakery/ddd/hotire/week2/domain/material/FermentedDough.java
  src/main/java/com/github/bakery/ddd/hotire/week2/domain/material/FermentedMaterial.java
  src/main/java/com/github/bakery/ddd/hotire/week2/domain/material/Flour.java
  src/main/java/com/github/bakery/ddd/hotire/week2/domain/material/FlourMaterial.java
  src/main/java/com/github/bakery/ddd/hotire/week2/domain/material/Material.java
  src/main/java/com/github/bakery/ddd/hotire/week2/domain/material/Water.java
  src/main/java/com/github/bakery/ddd/hotire/week2/domain/material/Yeast.java
  src/main/java/com/github/bakery/ddd/hotire/week2/domain/process/DoughMaterialProcessor.java
  src/main/java/com/github/bakery/ddd/hotire/week2/domain/process/FermentedMaterialProcessor.java
  src/main/java/com/github/bakery/ddd/hotire/week2/domain/process/MaterialProcessor.java
  src/main/java/com/github/bakery/ddd/hotire/week2/domain/process/PreparedMaterialProcessor.java
  src/test/java/com/github/bakery/ddd/hotire/week2/domain/material/DoughTest.java
Labels: enhancement, homework

#4 week 01 homework
  src/main/java/com/github/bakery/ddd/demo/week01/homework/README.MD
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/Baking.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/BlendingRecipe.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/DoughWater.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/MainMaterial.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/value/MainMaterialStep.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/value/Temperature.java
  src/test/java/com/github/bakery/ddd/demo/week01/homework/domain/BakingTest.java
Labels: homework

#6 1주차 과제
  src/main/java/com/github/bakery/ddd/wenmoe/domain/Bread.java
  src/main/java/com/github/bakery/ddd/wenmoe/domain/BreadState.java
  src/main/java/com/github/bakery/ddd/wenmoe/domain/BreadType.java
  src/main/java/com/github/bakery/ddd/wenmoe/domain/Dough.java
  src/main/java/com/github/bakery/ddd/wenmoe/domain/Flour.java
  src/main/java/com/github/bakery/ddd/wenmoe/domain/Mature.java
  src/main/java/com/github/bakery/ddd/wenmoe/domain/Water.java
Labels: homework

#7 1주차 과제
  src/main/java/com/github/bakery/ddd/yun0/week01/application/BreadService.java
  src/main/java/com/github/bakery/ddd/yun0/week01/domain/BakeryProcessor.java
  src/main/java/com/github/bakery/ddd/yun0/week01/domain/Dough.java
  src/main/java/com/github/bakery/ddd/yun0/week01/domain/Ingredients.java
  src/main/java/com/github/bakery/ddd/yun0/week01/domain/RipenedDough.java
  src/main/java/com/github/bakery/ddd/yun0/week01/domain/bread/Bread.java
  src/main/java/com/github/bakery/ddd/yun0/week01/domain/bread/BreadRepository.java
  src/main/java/com/github/bakery/ddd/yun0/week01/domain/flour/Flour.java
  src/main/java/com/github/bakery/ddd/yun0/week01/domain/flour/FlourRepository.java
  src/main/java/com/github/bakery/ddd/yun0/week01/domain/flour/FlourType.java
  src/main/java/com/github/bakery/ddd/yun0/week01/domain/recipe/BaseRecipe.java
  src/main/java/com/github/bakery/ddd/yun0/week01/requirement/Requirement.md
  src/test/java/com/github/bakery/ddd/yun0/week01/domain/BreadTest.java
Labels: homework

#9 add demo profile
  doc/demo/week02/README.MD
  src/main/resources/application.yml
Labels: enhancement

#10 2주차 과제
  build.gradle
  src/main/java/com/github/bakery/ddd/hotire/domain/Bread.java
  src/main/java/com/github/bakery/ddd/hotire/domain/BreadRepository.java
  src/main/java/com/github/bakery/ddd/hotire/domain/BreadStatus.java
  src/main/java/com/github/bakery/ddd/hotire/domain/BreadType.java
  src/main/java/com/github/bakery/ddd/hotire/domain/Recipe.java
  src/main/java/com/github/bakery/ddd/hotire/domain/material/Butter.java
  src/main/java/com/github/bakery/ddd/hotire/domain/material/Egg.java
  src/main/java/com/github/bakery/ddd/hotire/domain/material/FlourMaterial.java
  src/main/java/com/github/bakery/ddd/hotire/domain/material/MacaronFilling.java
  src/main/java/com/github/bakery/ddd/hotire/domain/material/Material.java
  src/main/java/com/github/bakery/ddd/hotire/domain/material/MaterialFactory.java
  src/main/java/com/github/bakery/ddd/hotire/domain/material/MaterialType.java
  src/main/java/com/github/bakery/ddd/hotire/domain/material/PizzaToping.java
  src/main/java/com/github/bakery/ddd/hotire/domain/material/Salt.java
  src/main/java/com/github/bakery/ddd/hotire/domain/material/SoboroHead.java
  src/main/java/com/github/bakery/ddd/hotire/domain/material/Water.java
  src/main/java/com/github/bakery/ddd/hotire/domain/material/Yeast.java
  src/main/java/com/github/bakery/ddd/hotire/persistent/adapter/BreadPersistentAdapter.java
  src/main/java/com/github/bakery/ddd/hotire/persistent/adapter/mapper/BreadJpaEntityMapper.java
  src/main/java/com/github/bakery/ddd/hotire/persistent/entity/BreadJpaEntity.java
  src/main/java/com/github/bakery/ddd/hotire/persistent/entity/MaterialJpaEmbeddable.java
  src/main/java/com/github/bakery/ddd/hotire/persistent/repository/BreadJpaEntityRepository.java
  src/main/java/com/github/bakery/ddd/hotire/util/JsonUtils.java
  src/main/java/com/github/bakery/ddd/hotire/util/MaterialUtils.java
  src/test/java/com/github/bakery/ddd/hotire/domain/material/MaterialFactoryTest.java
Labels: enhancement, homework

#11 2주차 과제
  src/main/java/com/github/bakery/ddd/demo/week01/homework/README.MD
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/Baking.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/BlendingRecipe.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/MainMaterial.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/baking/Baking.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/baking/BakingStep.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/baking/Bread.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/baking/DoughWater.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/baking/Temperature.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/baking/bakingprecess/BakingProcess.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/baking/bakingprecess/croissant/CroissantBakingProcess.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/baking/bakingprecess/croissant/CroissantDecorationBakingProcess.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/baking/bakingprecess/croissant/CroissantDoughBakingProcess.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/baking/bakingprecess/croissant/CroissantFermentBakingProcess.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/baking/bakingprecess/croissant/CroissantPrepareBakingProcess.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/baking/material/MainMaterial.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/baking/material/Material.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/baking/material/SubMaterial.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/baking/recipe/CroissantRecipe.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/baking/recipe/Recipe.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/baking/recipe/RecipeMainMaterial.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/domain/baking/recipe/RecipeSubMaterial.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/value/MainMaterialStep.java
  src/main/java/com/github/bakery/ddd/demo/week01/homework/value/Temperature.java
  src/main/resources/application.yml
  src/test/java/com/github/bakery/ddd/demo/week01/homework/domain/BakingTest.java
  src/test/java/com/github/bakery/ddd/demo/week01/homework/domain/baking/BakingTest.java
Labels: homework

#13 3주차 과제
  doc/homework/README.md
Labels: homework
